name: Publish to Github Packages

on:
  push:
    branches:
      - develop
      - chore/publish-to-jitpack
  workflow_dispatch:

jobs:
  build:
    name: Build & publish to Github Packages
    runs-on: macos-latest
    steps:
      - name: Set up JAVA 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Checkout source code
        uses: actions/checkout@v2.3.2
        with:
          submodules: recursive

      - name: Build
        run: ./gradlew assemble --stacktrace -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Release library
        run: ./gradlew core:publish -PGITHUB_USER=${{ secrets.CURRENT_GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
